### ISSUE TITLE
Deprecation of .ix indexer in Pandas

### ISSUE THREAD

**Issue by finlytics-hub** [CamDavidsonPilon/lifetimes#373]
Hi there,

I receive the following error when using the summary_data_from_transaction_data function:
AttributeError: 'DataFrame' object has no attribute 'ix'

I believe this is because IX indexing was deprecated starting from pandas 0.20.0 and removed in pandas 1.0.0. 

I believe I would need to use an older pandas version for the time being but is there any possibility updating the function to use .iloc instead of .ix?

Thanks

**Comment by finlytics-hub** [comment]
Apologies - I was able to resolve the issue.

Colab had an older Lifetimes version. After I updated it to 0.11.1, I was able to get the function work even with pandas 1.0.3.

Thanks
