### ISSUE TITLE
How to solve AttributeError: 'BetaGeoFitter' object has no attribute 'summary' when using v0.10.1?

### ISSUE THREAD

**Issue by yukioandre** [CamDavidsonPilon/lifetimes#401]
I was following the QuickStart Tutorial in https://lifetimes.readthedocs.io/en/latest/Quickstart.html. The first issue I had was:

    ConvergenceError: 
    The model did not converge. Try adding a larger penalizer to see if that helps convergence.

I then tried everything I found in posts like this one: https://github.com/CamDavidsonPilon/lifetimes/issues/259, but the only thing that worked was downgrading the package loaded. Now, I'm working with v0.10.1 instead of v.0.11.1. This downgrade fixed the problem with ConvergenceError, however I got a new issue when trying to get BetaGeoFitter summary. I tried running:

    from lifetimes import BetaGeoFitter, ModifiedBetaGeoFitter

    bgf = BetaGeoFitter(penalizer_coef=0.0)
    bgf.fit(data["frequency"], data["recency"], data["t"])

    bgf.summary

And got the error:

    AttributeError: 'BetaGeoFitter' object has no attribute 'summary'

Also, there's no 'summary' when checking dir(BetaGeoFitter).

Any ideas on how to fix the error? I can't upgrade to v0.11.1 because that would lead to the convergence error.
